### ISSUE TITLE
Update to 6.13.4

### ISSUE THREAD

**Issue by rwarren** [teamatldocker/confluence#67]
Enterprise version 6.13.4 came out on 2019-04-05:

https://confluence.atlassian.com/doc/issues-resolved-in-6-13-4-968672107.html

Not major security problem (like 6.13.3 was), but it would be good to update. Same goes for the 6.14 and 6.15 lines.

Note: I'd love to just do this as a PR, but am not sure how to properly build and test it. I'm also not sure how it works with dockerhub?

**Comment by jhult** [comment]
You should be able to build using something like this:

```
./buildscripts/buildImage.sh 6.15.2 latest Dockerfile en US
```

**Comment by rwarren** [comment]
Thanks @jhult. I was fiddling with `./scripts/build.sh`. What is reason for two of them?

**Comment by EugenMayer** [comment]
as with the jira image, i also bundle the confluence one https://cloud.docker.com/u/eugenmayer/repository/docker/eugenmayer/confluence with usually build in 1-2 days after release.

https://github.com/EugenMayer/docker-image-atlassian-confluence is the source. So for anyone in urgent need, you can go for those

**Comment by MikeNer** [comment]
Hey. I am quite new in docker and confluence. So we are running the docker confluence image from blacklableops. Because of some security problems we want to update our confluence version how is it possible to upgrade confluence in docker. Kind regards

**Comment by jhult** [comment]
This has been superseded. The latest version is now 6.15.9 and has been released on Docker Hub.
