### ISSUE TITLE
Http 404 not found after Confluence Update

### ISSUE THREAD

**Issue by MikeNer** [teamatldocker/confluence#72]
Hey,
After I have updated my confluence Version from 6.13.4 to 6.15.9 i am getting a 404 not found error. Any idea why?. Is it possible to do an extra tag on docker hub for 6.13.7?. Kind regards and many thanks Michael.

**Comment by jhult** [comment]
It looks like there is an issue using OpenJ9 as the JVM (see #73). I just flipped it back to HotSpot.

Try pulling the latest version now from Docker Hub (sha256:55f83ba6c564ef6439d72ccf10f13fbb570a4c8daef43cc92f98789d3487d276
).

**Comment by MikeNer** [comment]
Thanks. Great job :)
