### ISSUE TITLE
teamatldocker vs blacklabelops

### ISSUE THREAD

**Issue by brodkin** [teamatldocker/confluence#74]
Sorry to use the issue tracker this way, but we're still running 6.13.1 of the blacklabelops/confluence image. Can the teamatldocker 7.0+ images be safely used as a drop-in replacement?

**Comment by blacklabelops** [comment]
You have to read the Atlassian Confluence upgrade information. They are telling you, what to do when upgrading from Confluence 6.13.1 to the current version.

**Comment by jhult** [comment]
Generally, this should be a safe, drop-in replacement for `blacklabelops/confluence`. Let us know if you bump into any issues.
